owner: QRjet # Your GitHub organization or username, where this repository lives
repo: monitor-dev # The name of this repository

sites:
  - name: "[Web - Dev ] Consumer Web App"
    url: https://consumer.dev.truetale.io/
    
  - name: "[ Web - Dev ] Admin Web App"
    url: https://admin.dev.truetale.io/
    
  - name: "[ Web - Dev ] Partner Web App"
    url: https://partner.dev.truetale.io/
    
  - name: "[ Web - Dev ] Brands Web App"
    url: https://business.dev.truetale.io/
    
  - name: "[ Service - Dev ] Billing Service"
    url: https://api.dev.truetale.io/api/billing/health-check
    
  - name: "[ Service - Dev ] Consumer Service"
    url: https://api.dev.truetale.io/api/consumer/health-check
    
  - name: "[ Service - Dev ] Emails Service"
    url: https://api.dev.truetale.io/api/emails/health-check
    
  - name: "[ Service - Dev ] Gateway Service"
    url: https://api.dev.truetale.io/graphql/health-check
    
  - name: "[ Service - Dev ] Media Service"
    url: https://api.dev.truetale.io/api/media/health-check
    
  - name: "[ Service - Dev ] Orders Service"
    url: https://api.dev.truetale.io/api/orders/health-check
    
  - name: "[ Service - Dev ] orgAccounts Service"
    url: https://api.dev.truetale.io/api/org-accounts/health-check
    
  - name: "[ Service - Dev ] Pim Service"
    url: https://api.dev.truetale.io/api/pim/health-check
    
  - name: "[ Service - Dev ] Qr Codes Service"
    url: https://api.dev.truetale.io/api/qr-codes/health-check
    
  - name: "[ Service - Dev ] Reseller Service"
    url: https://api.dev.truetale.io/api/reseller/health-check
    
  - name: "[ Service - Dev ] Shopify Listener Service"
    url: https://api.dev.truetale.io/api/shopify-adapter-event-listener/health-check
    
  - name: "[ Service - Dev ] Shopify Sync"
    url: https://api.dev.truetale.io/api/shopify-adapter-sync/health-check
    
  - name: "[ Service - Dev ] Tags"
    url: https://api.dev.truetale.io/api/tags/health-check
    
  - name: "[ Service - Dev ] Templates"
    url: https://api.dev.truetale.io/api/templates/health-check
    
  - name: "[ Service - Dev ] Widgets"
    url: https://api.dev.truetale.io/api/widgets/health-check
    
  - name: "[ Service - Dev ] Admin"
    url: https://api.dev.truetale.io/api/admin/health-check
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
#   cname: demo.upptime.js.org
  baseUrl: /monitor-dev
#   logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Truetale Web Apps And Services Monitor Dev Environment
  introTitle: "**Truetale Monitor** monitor web apps and services."
  introMessage: A page that shows different web apps and services status based on **real-time** data
#   navbar:
#     - title: Status
#       href: /
#     - title: GitHub
#       href: https://github.com/$OWNER/$REPO
